FROM node:latest as prepare_package_json
WORKDIR /app
COPY . /app
RUN find /app -type d -name "node_modules" -exec rm -rf {} + \
  && find /app -type f -a \! \( -name "package.json" -o -name "package-lock.json" \) -delete \
  && find /app -type d -empty -delete

FROM node:latest as prepare_requirements_txt
WORKDIR /app
COPY . /app
RUN find /app -type d -name "node_modules" -exec rm -rf {} + \
  && find /app -type f -a \! \( -name "requirements.txt" -o -name "enumerate-requirements.ts" \) -delete \
  && find /app -type d -empty -delete

FROM node:latest as prepare_npm_i
WORKDIR /app
COPY --from=prepare_package_json /app /app
RUN echo "Installing NodeJS dependencies..." && npm i

FROM node:latest as prepare_requirements_txt_complete
WORKDIR /app
COPY --from=prepare_npm_i /app /app
COPY --from=prepare_requirements_txt /app /app
RUN npm run codegen:requirements \
  && mv /app/requirements.txt /tmp/requirements.txt \
  && rm -r /app \
  && mkdir /app \
  && mv /tmp/requirements.txt /app

FROM archlinux:base-devel
WORKDIR /app
RUN pacman -Sy --noconfirm python python-pip npm imagemagick librsvg potrace dbmate sudo git && pacman -Scc
COPY --from=prepare_requirements_txt_complete /app /app
RUN pip install -r /app/requirements.txt && rm /app/requirements.txt
ENV npm_config_cache=/app/.npm
CMD ["/bin/bash"]
