import { mdiApplicationExport } from '@mdi/js'; export const export_icon = { path: mdiApplicationExport, title: 'Export', size: 24 }
import { mdiApplicationImport } from '@mdi/js'; export const import_icon = { path: mdiApplicationImport, title: 'Import', size: 24 }
import { mdiArrowRight } from '@mdi/js'; export const rightarrow_icon = { path: mdiArrowRight, size: 24 }
import { mdiBiohazard } from '@mdi/js'; export const tumor_icon = { path: mdiBiohazard, title: 'Tumor', size: 24 }
import { mdiCameraMeteringMatrix } from '@mdi/js'; export const tissue_icon = { path: mdiCameraMeteringMatrix, title: 'Tissue', size: 24 }
import { mdiChartBar } from '@mdi/js'; export const barplot_icon = { path: mdiChartBar, title: 'Bar Plot', size: 24 }
import { mdiChartBoxOutline } from '@mdi/js'; export const plot_icon = { path: mdiChartBoxOutline, title: 'Plot', size: 24 }
import { mdiConnection } from '@mdi/js'; export const connection_icon = { path: mdiConnection, title: 'Connect', size: 24 }
import { mdiDna } from '@mdi/js'; export const gene_icon = { path: mdiDna, title: 'Gene', size: 24 }
import { mdiDownloadBoxOutline } from '@mdi/js'; export const download_icon = { path: mdiDownloadBoxOutline, title: 'Download', size: 24 }
import { mdiEmoticonCryOutline } from '@mdi/js'; export const disease_icon = { path: mdiEmoticonCryOutline, title: 'Disease', size: 24 }
import { mdiFile } from '@mdi/js'; export const file_icon = { path: mdiFile, title: 'File', size: 24 }
import { mdiFileLink } from '@mdi/js'; export const metadata_file_icon = { path: mdiFileLink, title: 'Metadata Matrix', size: 24 }
import { mdiFileSwap } from '@mdi/js'; export const file_transfer_icon = { path: mdiFileSwap, title: 'File Transfer', size: 24 }
import { mdiFileTable } from '@mdi/js'; export const datafile_icon = { path: mdiFileTable, title: 'Data File', size: 24 }
import { mdiFilter } from '@mdi/js'; export const filter_icon = { path: mdiFilter, title: 'Filter', size: 24 }
import { mdiFormatAlignJustify } from '@mdi/js'; export const set_icon = { path: mdiFormatAlignJustify, title: 'Set', size: 24 }
import { mdiFunctionVariant } from '@mdi/js'; export const func_icon = { path: mdiFunctionVariant, title: 'Function', size: 24 }
import { mdiHexagonMultiple } from '@mdi/js'; export const drug_icon = { path: mdiHexagonMultiple, title: 'Drug', size: 24 }
import { mdiHome } from '@mdi/js'; export const start_icon = { path: mdiHome, title: 'Start', size: 24 }
import { mdiHuman } from '@mdi/js'; export const phenotype_icon = { path: mdiHuman, title: 'Phenotype', size: 24 }
import { mdiImport } from '@mdi/js'; export const input_icon = { path: mdiImport, title: 'Input', size: 24 }
import { mdiLink } from '@mdi/js'; export const link_icon = { path: mdiLink, title: 'Link', size: 24 }
import { mdiMathNormBox } from '@mdi/js'; export const norm_icon = { path: mdiMathNormBox, title: 'Normalize', size: 24 }
import { mdiPlusBoxOutline } from '@mdi/js'; export const extend_icon = { path: mdiPlusBoxOutline, title: 'Extend', size: 24 }
import { mdiProgressAlert } from '@mdi/js'; export const status_alert_icon = { path: mdiProgressAlert, title: 'Error occurred', size: 24 }
import { mdiProgressCheck } from '@mdi/js'; export const status_complete_icon = { path: mdiProgressCheck, title: 'Completed', size: 24 }
import { mdiProgressClock } from '@mdi/js'; export const status_waiting_icon = { path: mdiProgressClock, title: 'Waiting for output...', size: 24 }
import { mdiProgressPencil } from '@mdi/js'; export const status_awaiting_input_icon = { path: mdiProgressPencil, title: 'Waiting for input', size: 24 }
import { mdiReorderVertical } from '@mdi/js'; export const transpose_icon = { path: mdiReorderVertical, title: 'Transpose', size: 24 }
import { mdiScatterPlot } from '@mdi/js'; export const scatterplot_icon = { path: mdiScatterPlot, title: 'Scatter Plot', size: 24 }
import { mdiSearchWeb } from '@mdi/js'; export const search_icon = { path: mdiSearchWeb, title: 'Search', size: 24 }
import { mdiSetNone } from '@mdi/js'; export const supervenn_icon = { path: mdiSetNone, title: 'Supervenn', size: 24 }
import { mdiShareVariant } from '@mdi/js'; export const share_icon = { path: mdiShareVariant, title: 'Publish', size: 24 }
import { mdiVariable } from '@mdi/js'; export const variable_icon = { path: mdiVariable, title: 'Variable', size: 24 }
import { mdiViewList } from '@mdi/js'; export const weighted_icon = { path: mdiViewList, title: 'Weighted', size: 24 }
import { mdiWebhook } from '@mdi/js'; export const pathway_icon = { path: mdiWebhook, title: 'Pathway', size: 24 }
import { IconSvgPaths20 } from '@blueprintjs/icons'
export const differential_expression_icon = { path: IconSvgPaths20.Changes.join(' '), title: 'Differential Expression', size: 20 }
// import Bp5Changes from '@blueprintjs/icons/src/generated/20px/paths/changes'; export const differential_expression_icon = { path: Bp5Changes.join(' '), title: 'Differential Expression', size: 20 }
export const delete_icon = { path: IconSvgPaths20.Delete.join(' '), title: 'Delete', size: 20 }
// import Bp5Delete from '@blueprintjs/icons/src/generated/20px/paths/delete'; export const delete_icon = { path: Bp5Delete.join(' '), title: 'Delete', size: 20 }
export const edit_icon = { path: IconSvgPaths20.Edit.join(' '), title: 'Edit', size: 20 }
// import Bp5Edit from '@blueprintjs/icons/src/generated/20px/paths/edit'; export const edit_icon = { path: Bp5Edit.join(' '), title: 'Edit', size: 20 }
export const error_icon = { path: IconSvgPaths20.Error.join(' '), title: 'Error', size: 20 }
// import Bp5Error from '@blueprintjs/icons/src/generated/20px/paths/error'; export const error_icon = { path: Bp5Error.join(' '), title: 'Error', size: 20 }
export const list_icon = { path: IconSvgPaths20.NumberedList.join(' '), title: 'Ordered List', size: 20 }
// import Bp5NumberedList from '@blueprintjs/icons/src/generated/20px/paths/numbered-list'; export const list_icon = { path: Bp5NumberedList.join(' '), title: 'Ordered List', size: 20 }
export const save_icon = { path: IconSvgPaths20.FloppyDisk.join(' '), title: 'Save', size: 20 }
// import Bp5FloppyDisk from '@blueprintjs/icons/src/generated/20px/paths/floppy-disk'; export const save_icon = { path: Bp5FloppyDisk.join(' '), title: 'Save', size: 20 }
export const fork_icon = { path: IconSvgPaths20.Fork.join(' '), title: 'Expand From this Step', size: 20 }
// import Bp5Fork from '@blueprintjs/icons/src/generated/20px/paths/fork'; export const fork_icon = { path: Bp5Fork.join(' '), title: 'Expand From this Step', size: 20 }
export const down_icon = { path: IconSvgPaths20.HorizontalBarChartAsc.join(' '), title: 'Down Regulating', size: 20, transform: 'translate(20 20) scale(-1 -1)' }
// import Bp5HorizontalBarChartAsc from '@blueprintjs/icons/src/generated/20px/paths/horizontal-bar-chart-asc'; export const down_icon = { path: Bp5HorizontalBarChartAsc.join(' '), title: 'Down Regulating', size: 20, transform: 'translate(20 20) scale(-1 -1)' }
export const up_icon = { path: IconSvgPaths20.HorizontalBarChartDesc.join(' '), title: 'Up Regulating', size: 20 }
// import Bp5HorizontalBarChartDesc from '@blueprintjs/icons/src/generated/20px/paths/horizontal-bar-chart-desc'; export const up_icon = { path: Bp5HorizontalBarChartDesc.join(' '), title: 'Up Regulating', size: 20 }
export const reaction_icon = { path: IconSvgPaths20.LabTest.join(' '), title: 'Reaction', size: 20 }
// import Bp5LabTest from '@blueprintjs/icons/src/generated/20px/paths/lab-test'; export const reaction_icon = { path: Bp5LabTest.join(' '), title: 'Reaction', size: 20 }
export const additional_info_icon = { path: IconSvgPaths20.ListDetailView.join(' '), title: 'Additional Information', size: 20 }
// import Bp5ListDetailView from '@blueprintjs/icons/src/generated/20px/paths/list-detail-view'; export const additional_info_icon = { path: Bp5ListDetailView.join(' '), title: 'Additional Information', size: 20 }
export const study_icon = { path: IconSvgPaths20.Manual.join(' '), title: 'Study', size: 20 }
// import Bp5Manual from '@blueprintjs/icons/src/generated/20px/paths/manual'; export const study_icon = { path: Bp5Manual.join(' '), title: 'Study', size: 20 }
export const gmt_icon = { path: IconSvgPaths20.PanelTable.join(' '), title: 'Gene Matrix Transpose', size: 20 }
// import Bp5PanelTable from '@blueprintjs/icons/src/generated/20px/paths/panel-table'; export const gmt_icon = { path: Bp5PanelTable.join(' '), title: 'Gene Matrix Transpose', size: 20 }
export const restart_icon = { path: IconSvgPaths20.Reset.join(' '), title: 'Restart', size: 20 }
// import Bp5Reset from '@blueprintjs/icons/src/generated/20px/paths/reset'; export const restart_icon = { path: Bp5Reset.join(' '), title: 'Restart', size: 20 }
export const view_in_graph_icon = { path: IconSvgPaths20.SendToGraph.join(' '), title: 'View in Graph', size: 20 }
// import Bp5SendToGraph from '@blueprintjs/icons/src/generated/20px/paths/send-to-graph'; export const view_in_graph_icon = { path: Bp5SendToGraph.join(' '), title: 'View in Graph', size: 20 }
export const view_report_icon = { path: IconSvgPaths20.SendToMap.join(' '), title: 'View Report', size: 20 }
// import Bp5SendToMap from '@blueprintjs/icons/src/generated/20px/paths/send-to-map'; export const view_report_icon = { path: Bp5SendToMap.join(' '), title: 'View Report', size: 20 }
export const minimize_icon = { path: IconSvgPaths20.Minimize.join(' '), title: 'Minimize', size: 20 }
// import Bp5Minimize from '@blueprintjs/icons/src/generated/20px/paths/minimize'; export const minimize_icon = { path: Bp5Minimize.join(' '), title: 'Minimize', size: 20 }
export const maximize_icon = { path: IconSvgPaths20.Maximize.join(' '), title: 'Maximize', size: 20 }
// import Bp5Maximize from '@blueprintjs/icons/src/generated/20px/paths/maximize'; export const maximize_icon = { path: Bp5Maximize.join(' '), title: 'Maximize', size: 20 }
export const fullscreen_icon = { path: IconSvgPaths20.Fullscreen.join(' '), title: 'Fullscreen', size: 20 }
// import Bp5Fullscreen from '@blueprintjs/icons/src/generated/20px/paths/fullscreen'; export const fullscreen_icon = { path: Bp5Fullscreen.join(' '), title: 'Fullscreen', size: 20 }
export const close_icon = { path: IconSvgPaths20.Cross.join(' '), title: 'Close', size: 20 }
// import Bp5Close from '@blueprintjs/icons/src/generated/20px/paths/close'; export const close_icon = { path: Bp5Close.join(' '), title: 'Close', size: 20 }