import { IconSvgPaths20 } from '@blueprintjs/icons'
export const fork_icon = { path: IconSvgPaths20.Fork.join(' '), title: 'Expand From this Step' }
export const view_in_graph_icon = { path: IconSvgPaths20.SendToGraph.join(' '), title: 'View in Graph' }
import { mdiArrowRight } from '@mdi/js'; export const rightarrow_icon = { path: mdiArrowRight }
import { mdiCameraMeteringMatrix } from '@mdi/js'; export const tissue_icon = { path: mdiCameraMeteringMatrix, title: 'Tissue' }
import { mdiChartBar } from '@mdi/js'; export const barchart_icon = { path: mdiChartBar, title: 'Bar Chart' }
import { mdiChartBoxOutline } from '@mdi/js'; export const plot_icon = { path: mdiChartBoxOutline, title: 'Plot' }
import { mdiDna } from '@mdi/js'; export const gene_icon = { path: mdiDna, title: 'Gene' }
import { mdiFile } from '@mdi/js'; export const file_icon = { path: mdiFile, title: 'File' }
import { mdiFileSwap } from '@mdi/js'; export const file_transfer_icon = { path: mdiFileSwap, title: 'File Transfer' }
import { mdiFileTable } from '@mdi/js'; export const datafile_icon = { path: mdiFileTable, title: 'Data File' }
import { mdiFunctionVariant } from '@mdi/js'; export const func_icon = { path: mdiFunctionVariant, title: 'Function' }
import { mdiHexagonMultiple } from '@mdi/js'; export const drug_icon = { path: mdiHexagonMultiple, title: 'Drug' }
import { mdiHome } from '@mdi/js'; export const start_icon = { path: mdiHome, title: 'Start' }
import { mdiImport } from '@mdi/js'; export const input_icon = { path: mdiImport, title: 'Input' }
import { mdiProgressAlert } from '@mdi/js'; export const status_alert_icon = { path: mdiProgressAlert, title: 'Error occurred' }
import { mdiProgressCheck } from '@mdi/js'; export const status_complete_icon = { path: mdiProgressCheck, title: 'Completed' }
import { mdiProgressClock } from '@mdi/js'; export const status_waiting_icon = { path: mdiProgressClock, title: 'Waiting for output...' }
import { mdiProgressPencil } from '@mdi/js'; export const status_awaiting_input_icon = { path: mdiProgressPencil, title: 'Waiting for input' }
import { mdiVariable } from '@mdi/js'; export const variable_icon = { path: mdiVariable, title: 'Variable' }
import { mdiViewList } from '@mdi/js'; export const weighted_icon = { path: mdiViewList, title: 'Weighted' }
