import * as dict from '@/utils/dict'
import { archs4_icon, gtex_icon, lincs_icon } from '@/icons'

export const Disease_backgrounds = [
  {
    name: 'Disease_Signatures_from_GEO_down_2014',
    label: 'Disease Signatures from GEO down',
    termType: 'Disease',
    termRe: /^(?<term>.+) (?<gse>[^ ]+)$/,
    termLabel: 'GEO Disease Signatures',
    termAssociation: 'Containing',
    ref: `\\ref{Gene Expression Omnibus, https://www.ncbi.nlm.nih.gov/geo/}`,
    icon: [],
  },
  {
    name: 'Disease_Signatures_from_GEO_up_2014',
    label: 'Disease Signatures from GEO up',
    termType: 'Disease',
    termRe: /^(?<term>.+) (?<gse>[^ ]+)$/,
    termLabel: 'GEO Disease Signatures',
    termAssociation: 'Containing',
    ref: `\\ref{Gene Expression Omnibus, https://www.ncbi.nlm.nih.gov/geo/}`,
    icon: [],
  },
  {
    name: 'GTEx_Aging_Signatures_2021',
    label: 'GTEx Aging Signatures 2021',
    termType: 'Disease',
    termRe: /^GTEx (?<term>.+)$/,
    termLabel: 'GeneRIF Rare Diseases',
    termAssociation: 'Containing',
    ref: `\\ref{Lonsdale, John, et al. "The genotype-tissue expression (GTEx) project." Nature genetics 45.6 (2013): 580-585. doi:/10.1038/ng.265}`,
    icon: [gtex_icon],
  },
  {
    name: 'Rare_Diseases_GeneRIF_ARCHS4_Predictions',
    label: 'Rare Diseases GeneRIF ARCHS4 Predictions',
    termType: 'Disease',
    termRe: /^(?<term>.+)$/,
    termLabel: 'GeneRIF Rare Diseases',
    termAssociation: 'Containing',
    ref: `\\ref{GeneRIF, https://www.ncbi.nlm.nih.gov/gene/about-generif}`,
    icon: [],
  },
  {
    name: 'Rare_Diseases_GeneRIF_Gene_Lists',
    label: 'Rare Diseases GeneRIF Gene Lists',
    termType: 'Disease',
    termRe: /^(?<term>.+)$/,
    termLabel: 'GeneRIF Rare Diseases',
    termAssociation: 'Containing',
    ref: `\\ref{GeneRIF, https://www.ncbi.nlm.nih.gov/gene/about-generif}`,
    icon: [],
  },
]

export const Drug_backgrounds = [
  {
    name: 'LINCS_L1000_Chem_Pert_Consensus_Sigs',
    label: 'LINCS L1000 Chem Pert Consensus Sigs',
    termType: 'Drug',
    termRe: /^(?<term>.+) (?<direction>Up|Down)$/,
    termLabel: 'L1000 Chem Pert Signatures',
    termAssociation: 'Containing',
    ref: `\\ref{John Erol Evangelista, Daniel J B Clarke, Zhuorui Xie, Alexander Lachmann, Minji Jeon, Kerwin Chen, Kathleen M Jagodnik, Sherry L Jenkins, Maxim V Kuleshov, Megan L Wojciechowicz, Stephan C Schürer, Mario Medvedovic, Avi Ma’ayan, SigCom LINCS: data and metadata search engine for a million gene expression signatures, Nucleic Acids Research, Volume 50, Issue W1, 5 July 2022, Pages W697–W709, doi:10.1093/nar/gkac328}`,
    icon: [lincs_icon],
  },
  {
    name: 'LINCS_L1000_Chem_Pert_up',
    label: 'LINCS L1000 Chem Pert Up',
    termType: 'Drug',
    termRe: /^(?<desc>.+?-(?<term>.+)-(?<concentration>.+?))$/,
    termLabel: 'L1000 Chem Pert Signatures',
    termAssociation: 'Containing',
    ref: `\\ref{Subramanian A, et al. A Next Generation Connectivity Map: L1000 Platform And The First 1,000,000 Profiles. Cell. 2017/12/1. 171(6):1437–1452}`,
    icon: [lincs_icon],
  },
  {
    name: 'LINCS_L1000_Chem_Pert_down',
    label: 'LINCS L1000 Chem Pert Down',
    termType: 'Drug',
    termRe: /^(?<desc>.+?-(?<term>.+)-(?<concentration>.+?))$/,
    termLabel: 'L1000 Chem Pert Signatures',
    termAssociation: 'Containing',
    ref: `\\ref{Subramanian A, et al. A Next Generation Connectivity Map: L1000 Platform And The First 1,000,000 Profiles. Cell. 2017/12/1. 171(6):1437–1452}`,
    icon: [lincs_icon],
  },
]

export const Pathway_backgrounds = [
  {
    name: 'GO_Biological_Process_2021',
    label: 'GO Biological Process 2021',
    termType: 'BiologicalProcess',
    termRe: /^(?<term>.+)\((?<xref>.+?)\)$/,
    termLabel: 'GO Biological Processes',
    termAssociation: 'Containing',
    ref: `\\ref{Ashburner, M et al. “Gene ontology: tool for the unification of biology. The Gene Ontology Consortium.” Nature genetics vol. 25,1 (2000): 25-9. doi:10.1038/75556}`,
    icon: [],
  },
  {
    name: 'KEGG_2019_Human',
    label: 'KEGG 2019 Human',
    termType: 'Pathway',
    termRe: /^(?<term>.+)$/,
    termLabel: 'KEGG Pathways',
    termAssociation: 'Containing',
    extra: {
      organism: 'human',
    },
    ref: `\\ref{Kanehisa, Minoru. “Toward understanding the origin and evolution of cellular organisms.” Protein science : a publication of the Protein Society vol. 28,11 (2019): 1947-1951. doi:10.1002/pro.3715}`,
    icon: [],
  },
  {
    name: 'KEGG_2019_Mouse',
    label: 'KEGG 2019 Mouse',
    termType: 'Pathway',
    termRe: /^(?<term>.+)$/,
    termLabel: 'KEGG Pathways',
    termAssociation: 'Containing',
    extra: {
      organism: 'mouse',
    },
    ref: `\\ref{Kanehisa, Minoru. “Toward understanding the origin and evolution of cellular organisms.” Protein science : a publication of the Protein Society vol. 28,11 (2019): 1947-1951. doi:10.1002/pro.3715}`,
    icon: [],
  },
  {
    name: 'KEGG_2021_Human',
    label: 'KEGG 2021 Human',
    termType: 'Pathway',
    termRe: /^(?<term>.+)$/,
    termLabel: 'KEGG Pathways',
    termAssociation: 'Containing',
    extra: {
      organism: 'human',
    },
    ref: `\\ref{Minoru Kanehisa, Miho Furumichi, Yoko Sato, Masayuki Kawashima, Mari Ishiguro-Watanabe, KEGG for taxonomy-based analysis of pathways and genomes, Nucleic Acids Research, Volume 51, Issue D1, 6 January 2023, Pages D587–D592, doi:10.1093/nar/gkac963}`,
    icon: [],
  },
  {
    name: 'MSigDB_Hallmark_2020',
    label: 'MSigDB Hallmark 2020',
    termType: 'Pathway',
    termRe: /^(?<term>.+)$/,
    termLabel: 'MSigDB Hallmark Gene Sets',
    termAssociation: 'Containing',
    ref: `\\ref{Subramanian, Aravind et al. “Gene set enrichment analysis: a knowledge-based approach for interpreting genome-wide expression profiles.” Proceedings of the National Academy of Sciences of the United States of America vol. 102,43 (2005): 15545-50. doi:10.1073/pnas.0506580102}`,
    icon: [],
  },
  {
    name: 'WikiPathway_2021_Human',
    label: 'WikiPathway 2021 Human',
    termType: 'Pathway',
    termRe: /^(?<term>.+)$/,
    termLabel: 'WikiPathways',
    termAssociation: 'Containing',
    extra: {
      organism: 'human',
    },
    ref: `\\ref{Marvin Martens, Ammar Ammar, Anders Riutta, Andra Waagmeester, Denise N Slenter, Kristina Hanspers, Ryan A. Miller, Daniela Digles, Elisson N Lopes, Friederike Ehrhart, Lauren J Dupuis, Laurent A Winckers, Susan L Coort, Egon L Willighagen, Chris T Evelo, Alexander R Pico, Martina Kutmon, WikiPathways: connecting communities, Nucleic Acids Research, Volume 49, Issue D1, 8 January 2021, Pages D613–D621, doi:10.1093/nar/gkaa1024}`,
    icon: [],
  },
  {
    name: 'WikiPathways_2019_Human',
    label: 'WikiPathways 2019 Human',
    termType: 'Pathway',
    termRe: /^(?<term>.+) (?<id>[^ ]+)$/,
    termLabel: 'WikiPathways',
    termAssociation: 'Containing',
    extra: {
      organism: 'human',
    },
    ref: `\\ref{Marvin Martens, Ammar Ammar, Anders Riutta, Andra Waagmeester, Denise N Slenter, Kristina Hanspers, Ryan A. Miller, Daniela Digles, Elisson N Lopes, Friederike Ehrhart, Lauren J Dupuis, Laurent A Winckers, Susan L Coort, Egon L Willighagen, Chris T Evelo, Alexander R Pico, Martina Kutmon, WikiPathways: connecting communities, Nucleic Acids Research, Volume 49, Issue D1, 8 January 2021, Pages D613–D621, doi:10.1093/nar/gkaa1024}`,
    icon: [],
  },
  {
    name: 'WikiPathways_2019_Mouse',
    label: 'WikiPathways 2019 Mouse',
    termType: 'Pathway',
    termRe: /^(?<term>.+)$/,
    termLabel: 'WikiPathways',
    termAssociation: 'Containing',
    extra: {
      organism: 'mouse',
    },
    ref: `\\ref{Marvin Martens, Ammar Ammar, Anders Riutta, Andra Waagmeester, Denise N Slenter, Kristina Hanspers, Ryan A. Miller, Daniela Digles, Elisson N Lopes, Friederike Ehrhart, Lauren J Dupuis, Laurent A Winckers, Susan L Coort, Egon L Willighagen, Chris T Evelo, Alexander R Pico, Martina Kutmon, WikiPathways: connecting communities, Nucleic Acids Research, Volume 49, Issue D1, 8 January 2021, Pages D613–D621, doi:10.1093/nar/gkaa1024}`,
    icon: [],
  },
]

export const Phenotype_backgrounds = [
  {
    name: 'GWAS_Catalog_2019',
    label: 'GWAS Catalog 2019',
    termType: 'Phenotype',
    termRe: /^(?<term>.+)$/,
    termLabel: 'GWAS Phenotypes',
    termAssociation: 'Associated with',
    extra: {
      organism: 'human',
    },
    ref: `\\ref{https://www.ebi.ac.uk/gwas}`,
    icon: [],
  },
  {
    name: 'UK_Biobank_GWAS_v1',
    label: 'UK Biobank GWAS v1',
    termType: 'Phenotype',
    termRe: /^(?<term>.+)$/,
    termLabel: 'UK Biobank Phenotypes',
    termAssociation: 'Associated with',
    extra: {
      organism: 'human',
    },
    ref: `\\ref{https://www.ukbiobank.ac.uk/tag/gwas/}`,
    icon: [],
  },
  {
    name: 'ClinVar_2019',
    label: 'ClinVar 2019',
    termType: 'Phenotype',
    termRe: /^(?<term>.+)$/,
    termLabel: 'ClinVar Phenotypes',
    termAssociation: 'Associated with',
    extra: {
      organism: 'human',
    },
    ref: `\\ref{https://www.ncbi.nlm.nih.gov/clinvar/}`,
    icon: [],
  },
  {
    name: 'Human_Phenotype_Ontology',
    label: 'Human Phenotype Ontology',
    termType: 'Phenotype',
    termRe: /^(?<term>.+)$/,
    termLabel: 'Human Phenotypes',
    termAssociation: 'Associated with',
    extra: {
      organism: 'human',
    },
    ref: `\\ref{http://www.human-phenotype-ontology.org/}`,
    icon: [],
  },
  {
    name: 'MGI_Mammalian_Phenotype_Level_4_2019',
    label: 'MGI Mammalian Phenotype Level 4 2019',
    termType: 'Phenotype',
    termRe: /^(?<term>.+)$/,
    termLabel: 'MGI Mammalian Phenotypes',
    termAssociation: 'Associated with',
    extra: {
      organism: 'mouse',
    },
    ref: `\\ref{http://www.informatics.jax.org/}`,
    icon: [],
  },
]

export const Tissue_backgrounds = [
  {
    name: 'GTEx_Tissues_V8_2023',
    label: 'GTEx Tissues V8 2023',
    termType: 'Tissue',
    termRe: /^(?<term>.+) (?<gender>[^ ]+) (?<age>[^ ]+) (?<direction>[^ ]+)$/,
    termLabel: 'GTEx Tissue Signatures',
    termAssociation: 'Containing',
    extra: {
      organism: 'human',
    },
    ref: `\\ref{Lonsdale, John, et al. "The genotype-tissue expression (GTEx) project." Nature genetics 45.6 (2013): 580-585. doi:10.1038/ng.265home/}`,
    icon: [gtex_icon],
  },
  {
    name: 'ARCHS4_Tissues',
    label: 'ARCHS4 Tissues',
    termType: 'Tissue',
    termRe: /^(?<term>.+)$/,
    termLabel: 'ARCHS4 Tissue Signatures',
    termAssociation: 'Containing',
    ref: `\\ref{Lachmann A, Torre D, Keenan AB, Jagodnik KM, Lee HJ, Wang L, Silverstein MC, Ma’ayan A. Massive mining of publicly available RNA-seq data from human and mouse. Nature Communications 9. Article number: 1366 (2018), doi:10.1038/s41467-018-03751-6}`,
    icon: [archs4_icon],
  },
]

export const Gene_backgrounds = [
  {
    name: 'ChEA_2022',
    label: 'ChEA 2022',
    termType: 'TranscriptionFactor',
    termRe: /^(?<term>[^ ]+?) (?<origin>.+) (?<organism>[^ ]+)$/,
    termLabel: 'ChEA Transcription Factors',
    termAssociation: 'Targeting',
    ref: `\\ref{Keenan AB, Torre D, Lachmann A, Leong AK, Wojciechowicz M, Utti V, Jagodnik K, Kropiwnicki E, Wang Z, Ma'ayan A (2019) ChEA3: transcription factor enrichment analysis by orthogonal omics integration. Nucleic Acids Research. doi: 10.1093/nar/gkz446}`,
    icon: [],
  },
  {
    name: 'ENCODE_TF_ChIP-seq_2015',
    label: 'ENCODE TF ChIP-seq 2015',
    termType: 'TranscriptionFactor',
    termRe: /^(?<term>[^ ]+) (?<origin>.+) (?<organism>[^ ]+)$/,
    termLabel: 'ENCODE Transcription Factors',
    termAssociation: 'Targeting',
    ref: `\\ref{http://genome.ucsc.edu/ENCODE/downloads.html}`,
    icon: [],
  },
  {
    name: 'ARCHS4_TFs_Coexp',
    label: 'ARCHS4 TF Co-Expression',
    termType: 'TranscriptionFactor',
    termRe: /^(?<term>[^ ]+) (?<organism>[^ ]+) (?<origin>.+)$/,
    termLabel: 'ARCHS4 Transcription Factors',
    termAssociation: 'Correlated with',
    ref: `\\ref{Lachmann A, Torre D, Keenan AB, Jagodnik KM, Lee HJ, Wang L, Silverstein MC, Ma’ayan A. Massive mining of publicly available RNA-seq data from human and mouse. Nature Communications 9. Article number: 1366 (2018), doi:10.1038/s41467-018-03751-6}`,
    icon: [archs4_icon],
  },
  {
    name: 'LINCS_L1000_CRISPR_KO_Consensus_Sigs',
    label: 'LINCS L1000 CRISPR KO Consensus Sigs',
    termType: 'Gene',
    termRe: /^(?<term>.+) (?<direction>.+)$/,
    termLabel: 'L1000 CRISPR KO Signatures',
    termAssociation: 'Containing',
    ref: `\\ref{John Erol Evangelista, Daniel J B Clarke, Zhuorui Xie, Alexander Lachmann, Minji Jeon, Kerwin Chen, Kathleen M Jagodnik, Sherry L Jenkins, Maxim V Kuleshov, Megan L Wojciechowicz, Stephan C Schürer, Mario Medvedovic, Avi Ma’ayan, SigCom LINCS: data and metadata search engine for a million gene expression signatures, Nucleic Acids Research, Volume 50, Issue W1, 5 July 2022, Pages W697–W709, doi:10.1093/nar/gkac328}`,
    icon: [lincs_icon],
  },
]

export const backgrounds = dict.init([
  ...Disease_backgrounds,
  ...Drug_backgrounds,
  ...Pathway_backgrounds,
  ...Phenotype_backgrounds,
  ...Tissue_backgrounds,
  ...Gene_backgrounds,
].map((value) => ({ key: value.name, value })))
